services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - autoforge
      - interview-agent
      - auth-mfe
      - org-mfe
  autoforge:
    build:
      context: .
      dockerfile: docker/Dockerfile.AutoForge
    container_name: autoforge
    restart: unless-stopped
  interview-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.interview-agent
    container_name: interview-agent
    restart: unless-stopped
  auth-mfe:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth-mfe
    container_name: auth-mfe
    restart: unless-stopped
  org-mfe:
    build:
      context: .
      dockerfile: docker/Dockerfile.org-mfe
    container_name: org-mfe
    restart: unless-stopped